# Generated by Django 5.2.5 on 2025-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=100)),
                ('contenido_html', models.TextField()),
            ],
        ),
    ]
